languageCode = "en-us"
title = "Eric Y. Lai Portfolio"
baseurl = "http://example.org/"
theme = "prologue"

[params]
  name = "Eric Y. Lai"
  school = "Stevens Institute of Technology"
  copyright = "2020 Eric Lai"

# About Me
[[params.about_me]]
  title = ""
  text = "Hello, my name is Eric Lai. I’m currently studying at Stevens Institute of Technology towards a B.S in Computer Science and a Minor in Pure & Applied Mathematics. I am particularly interested in theory and systems programming, but I’ll generally enjoy learning about anything. I’ve been fortunate enough to intern with a couple companies, allowing me to develop my skills under some really talented engineers. I plan to continue exploring the different sectors of industry and hope to make meaningful contributions wherever I end up."

[[params.about_me]]
  title = "Why Computer Science?"
  text = "After reading several of my peers’ personal statements about their aspired fields of study, I realized I lacked one thing that they all seemingly had in common; I never had an eye-opening “Eureka!” moment that inspired me to pursue Computer Science. It would be ingenuine of me to say that I did and honestly, I’m not entirely sure if that really was the case for everyone else around me. My path towards CS has mostly been a slow progression of discovering my interests, with a bit of Life’s randomness sprinkled in. From a young age, I was aware that my strengths lay in maths and sciences, so I knew I was probably going to end up in something STEM-related. In junior year of high school, I spontaneously replaced my lunch period with an AP Computer Science course that I didn’t even fulfill the prerequisites for. For anyone else, I probably would’ve advised against this type of impulsive decision but luckily it worked out for me. One thing led to another and I joined a robotics team, attended a couple hackathons, and started pursuing a Computer Science degree. I’m currently in my fourth year out of a five year cooperative education program and I’m loving everything I’m learning. I’ve found out that I thrived on creative problem solving and CS became a fitting outlet for me to exercise my problem solving skills while making the most out of my affinity for math and science. Sometimes a family member or friend will raise the point that I might’ve liked another STEM field just as much as I do CS. They might be right, or they might not. At this point, it doesn’t really matter to me because I’m enjoying my major too much to switch." 

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/Yun-L"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/eric-lai-a19b04150/"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:yun26603020@gmail.com"


# Portfolio column one

[[params.portfolio1]]
  title = "Placeholder 1"
  alt = ""
  source = "img/pf1.jpg"
  url = "#"


# Portfolio column two

[[params.portfolio2]]
  title = "Placeholder 2"
  alt = ""
  source = "img/pf2.jpg"
  url = "#"


# Portfolio column 3

[[params.portfolio3]]
  title = "Placeholder 3"
  alt = ""
  source = "img/pic05.jpg"
  url = "#"
